### ISSUE TITLE
Some adjustments

### ISSUE THREAD

**Issue by TurtleTony** [sgofferj/CM3588-NAS-case#2]
Hi there! First of all, thank you so much, the case is amazing :-) A friend of mine printed it with the following settings:

Printer: Anycubic Vyper
Slicer: Ultimaker Cura 5.2.2
Filament: Eryone White PLA 1,75 +- 0.03

0.16mm, 10% Infill, 200°C, 60.0mm/s

I've attached some pictures of how the board fits and firmly sits in the case. The screw-holes are somewhat misaligned, but I didn't even need the screws at all.

The slot for the sd card was a little too narrow so I had to sand it down a bit to get proper access to it. Otherwise all the I/O seems to be accessible to me.

An issue I had: The buttons don't work at all, they are a lot deeper than you'd think so they need to be at least 2mm longer to be able to use.

A feature idea: The heatsink has mounting holes for what I believe to be a 40mm fan, you could add an appropriate hole above this area to the lid, so that a fan could suck air from the lid and blow it out the side holes. I tried running the board cooled passively, but my SSDs got over 60 degree when utilized and had an idle temp of around 45-50°, that's not something to run 24/7 I feel like, so a fan hole would definitely add some more options.

![photo_1_2024-04-13_17-52-13](https://github.com/sgofferj/CM3588-NAS-case/assets/44305381/83152d07-48a0-4b07-836e-0dd840ff5b10)
![photo_2_2024-04-13_17-52-13](https://github.com/sgofferj/CM3588-NAS-case/assets/44305381/4f58a5bb-da08-4176-b323-b34e44c0fd9f)
![photo_3_2024-04-13_17-52-13](https://github.com/sgofferj/CM3588-NAS-case/assets/44305381/c79d1c19-6398-4672-9146-999c1d92526c)
![photo_4_2024-04-13_17-52-13](https://github.com/sgofferj/CM3588-NAS-case/assets/44305381/29e98190-1171-4786-a3e3-1b567b2d2b51)
![photo_5_2024-04-13_17-52-13](https://github.com/sgofferj/CM3588-NAS-case/assets/44305381/190d0f22-9514-42c3-9ab6-3268760a5307)
![photo_6_2024-04-13_17-52-13](https://github.com/sgofferj/CM3588-NAS-case/assets/44305381/fcd995a0-b001-4cf6-ac36-272c9edba9af)
![photo_7_2024-04-13_17-52-13](https://github.com/sgofferj/CM3588-NAS-case/assets/44305381/a10e261d-a6b8-4422-9ee3-010da3e609ab)

**Comment by TurtleTony** [comment]
Depending on the type of cable used, the case might benefit from slightly larger slots for the USB and HDMI connectors. Although sanding them down works too.

**Comment by sgofferj** [comment]
I'm using 2 Noctua 40mm fans to blow across the whole board including CPU and SSD. That works fairly well. Your version seems to be a little bit enlarged compared to mine. Maybe our printers have different settings. I designed it so that the ports should fit through the hole, not sit behind them. I like how you changed the air vents. I was a little too lazy to make them pretty but I might still change that :D

**Comment by TurtleTony** [comment]
Ooooh, I'm so sorry, I totally sent this to the wrong repository. Yours was the Case with the Fan inserts included, right! I'll make sure to send my feedback to the correct repository 🤦‍♂️

Looking at it, I might also print your version and see which I like better, thank you for providing this! :-)
